main:
	gcc -o HuSH hush.c utils.c commands/echo.c commands/cd.c commands/pwd.c commands/repeat.c commands/fexec.c commands/bexec.c commands/pinfo.c commands/history.c commands/ls.c commands/jobs.c commands/sig.c commands/bg.c commands/fg.c commands/replay.c
